Add support to {match} replacement in message and "both" type
arkon/issue-closer-action pull request #29
Opened 2021-05-17 23:26 UTC by alessandrojean

Should now accept rules like this (in theory):

```json
{
  "type": "both",
  "regex":".*(mangago|mangafox).*",
  "caseIgnore": true,
  "message": "{match} will not be added back as it is too difficult to maintain"
}
```

I did not bump the version in package now because it was not tested.

2021-05-17 23:38 UTC, arkon reviewed
You could in theory test it in your fork by creating issues (that's what I do here). You'd need to make sure to actually build it first though (i.e. run `npm run build`).

2021-05-17 23:38 UTC, arkon commented on src/main.ts
> +  caseIgnore?: boolean;
`ignoreCase`

2021-05-17 23:38 UTC, arkon commented on src/main.ts
> +function check(patternString: string, texts: Array<string> | undefined, caseIgnore: boolean = false): Array<RegExpMatchArray> {
You don't do anything with the `caseIgnore` argument.

2021-05-17 23:38 UTC, arkon commented on src/main.ts
> +        let texts: Array<string> = [payload?.issue?.title];
Nitpick: use `string[]` rather than `Array<string>`

2021-05-17 23:38 UTC, arkon commented on src/main.ts
> +        const regexMatches = check(rule.regex, texts, rule.caseIgnore || false);
Isn't the `|| false` unnecessary if you're already defaulting it in the function parameters?

2021-05-17 23:38 UTC, arkon commented on src/main.ts
> +        const message = rule.message.replace(/\{match\}/g, match)
Missing semicolon

2021-05-17 23:42 UTC, alessandrojean commented
I will change the things and test on my repo too.

2021-05-17 23:43 UTC, alessandrojean commented on src/main.ts
> +function check(patternString: string, texts: Array<string> | undefined, caseIgnore: boolean = false): Array<RegExpMatchArray> {
Woops, I forgot.

2021-05-17 23:57 UTC, alessandrojean commented
I tried to test on my repo, but it doesn't seen to be checking the new rule, even when I added the branch name in the `ref` parameter on the checkout action.

2021-05-17 23:59 UTC, arkon commented
It's likely using the workflow from the default branch, not whatever branch you're creating the PR from.

2021-05-18 00:01 UTC, alessandrojean commented
Probably. I will modify the file in the default branch and see if it works.

2021-05-18 00:13 UTC, alessandrojean commented
I managed to test, but it's not matching. I will see if I can find the error.

2021-05-18 00:22 UTC, alessandrojean commented
Tested now and working as expected :)

I will update the examples and bump the version.

2021-05-18 00:26 UTC, alessandrojean commented
Should be fine now and ready to merge.

2021-05-18 00:29 UTC, arkon requested changes

2021-05-18 00:29 UTC, arkon commented on .github/workflows/test.yml
> +      # uses: arkon/issue-closer-action@v3.3
Can you revert the version changes? I'll do it separately so I can make the release properly.

2021-05-18 00:29 UTC, arkon commented on README.md
> +- `message`: ES2015-style template literal evaluated with the issue webhook payload in context (see [payload example](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-15
Can you update the documentation in `action.yml` too?

2021-05-18 00:29 UTC, arkon commented on src/main.ts
> +    ?.map(text => {
Can you add comment(s) about what's happening in here?

2021-05-18 00:40 UTC, alessandrojean commented on src/main.ts
> +    ?.map(text => {
Sure.

2021-05-18 00:50 UTC, alessandrojean commented on .github/workflows/test.yml
> +      # uses: arkon/issue-closer-action@v3.3
Sure.

2021-05-18 00:51 UTC, alessandrojean commented
Documentation updated and version changes reverted.

2021-05-18 01:01 UTC, arkon approved these changes

2021-05-18 01:01 UTC, merged

2021-05-18 01:05 UTC, arkon commented
Thanks!

Release in v3.3.